### ISSUE TITLE
Give user chance to login if token no longer valid

### ISSUE THREAD

**Issue by retog** [linked-solutions/fuseki-oidc#17]
![image](https://user-images.githubusercontent.com/110756/57146251-2fd53e80-6dc5-11e9-9ee9-039ed1c9ffd7.png)
Currently I manually have to remove the fragment identifier before I can log in again.

**Comment by nleanba** [comment]
For me it works fine to just click the `Login`-Button again.

**Comment by retog** [comment]
You're right @nleanba. that works.
